name: "Update screenshots"

on: workflow_dispatch

jobs:
  update_screens:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appearance: [dark, light]
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - run: yarn --frozen-lockfile --ignore-scripts
      - name: Install browser for E2E
        run: yarn --cwd node_modules/playwright-${{ matrix.browser }} run install
      - name: Install deps for playwright
        run: npx playwright install-deps ${{ matrix.browser }}
      - name: Update screenshots
        run: yarn test:e2e -u
        env:
          APPEARANCE: ${{ matrix.appearance }}
          BROWSER: ${{ matrix.browser }}
      - name: Push updated screenshots
        uses: Wandalen/wretry.action@v1.0.11
        with:
          action: EndBug/add-and-commit@v9
          with:
            # dangerfile depends on this message
            message: "CHORE: Update screenshots"
            add: "./**/*.png"
            pull: "--rebase"
          attempt_limit: 6
          attempt_delay: 10000
